### ISSUE TITLE
Go to top hover is in chinese

### ISSUE THREAD

**Issue by Haroenv** [stbenjam/stbenjam.github.io#16]
relevant code: https://github.com/stbenjam/stbenjam.github.io/blob/d48b8db310739839c7be8e370fcce3fad49a74e8/_layouts/default.html#L17-L22

**Comment by stbenjam** [comment]
Thanks, the theme was designed by a Chinese guy.  I removed the link entirely, as it didn't even seem to work for me.

Thanks @Haroenv !

**Comment by Haroenv** [comment]
You're welcome
